---
- include: ../../scaleio-common/tasks/install_scaleio.yml

- name: copy scaleio_sdc_driver_sync_user_private_rsa_key_src for driver_sync.conf
  copy: src="{{ scaleio_sdc_driver_sync_user_private_rsa_key_src }}" dest="{{ scaleio_sdc_driver_sync_user_private_rsa_key_dest }}" mode="0600" owner="root" group="root"
  when: scaleio_sdc_driver_sync_user_private_rsa_key_src is defined

- name: copy scaleio_sdc_driver_sync_repo_public_rsa_key_src for driver_sync.conf
  copy: src="{{ scaleio_sdc_driver_sync_repo_public_rsa_key_src }}" dest="{{ scaleio_sdc_driver_sync_repo_public_rsa_key_dest }}" mode="0600" owner="root" group="root"
  when: scaleio_sdc_driver_sync_repo_public_rsa_key_src is defined

- name: copy scaleio_sdc_driver_sync_emc_public_gpg_key_src for driver_sync.conf
  copy: src="{{ scaleio_sdc_driver_sync_emc_public_gpg_key_src }}" dest="{{ scaleio_sdc_driver_sync_emc_public_gpg_key_dest }}" mode="0600" owner="root" group="root"
  when: scaleio_sdc_driver_sync_emc_public_gpg_key_src is defined

- name: copy driver_sync.conf template in place
  template: src="driver_sync.conf.j2" dest="/bin/emc/scaleio/scini_sync/driver_sync.conf" mode="0600" owner="root" group="root"
  notify: restart scini
