# Admin password for the gateway
scaleio_gateway_admin_password: 'Cluster1!'
# Is the gateway redundant (will install keepalived)
scaleio_gateway_is_redundant: false
# Virtual IP if redundant
scaleio_gateway_virtual_ip: ''
# Interface to attach the virtual ip
scaleio_gateway_virtual_interface: eth1
# Skip Java installation for ScaleIO (assume it's on the system)
scaleio_skip_java: false
file_glob_name: gateway
scaleio_role_environment:
        - key: "MDM_IP"
          value: "{{ scaleio_mdm_ips }}"
        - key: "GATEWAY_ADMIN_PASSWORD"
          value: "{{ scaleio_gateway_admin_password }}"
