# Admin password for the gateway
scaleio_gateway_admin_password: 'Cluster1!'
# Is the gateway redundant (will install keepalived)
scaleio_gateway_is_redundant: false
# Virtual IP if redundant
scaleio_gateway_virtual_ip: ''
# Interface to attach the virtual ip
scaleio_gateway_virtual_interface: eth1
# Skip Java installation for ScaleIO (assume it's on the system)
scaleio_skip_java: false
